services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - curl https://cli-assets.heroku.com/install.sh | sh
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

script:
    - docker build -t ccrespo/travel-agency .
    - docker tag ccrespo/travel-agency registry.heroku.com/$HEROKU_APP/web 

deploy:
  provider: script
  script:
    docker push ccrespo/travel-agency;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP;