
FROM node:alpine as builder

RUN npm install typescript -g

WORKDIR /app

COPY package.json yarn.lock tsconfig.json  ./
COPY server/ ./server

RUN yarn config set strict-ssl false 
RUN yarn install --frozen-lockfile --prefer-offline

RUN yarn build:server


FROM node:alpine
WORKDIR /app

COPY --from=0 ./app/server/dist ./server/dist
COPY package.json yarn.lock ./
COPY server/package.json ./server
RUN yarn install --frozen-lockfile --production

CMD ["npm", "run", "start:server"]